<?php

    return [

            "Blog" => 'Blog' ,
            "Building content for the site" => 'Building content for the site' ,
            "Building website content means having a professional strategy to create the content on your website pages that is compatible with your goals and the aspirations of your customers, providing information that benefits visitors and followers, using content marketing as an effective means for digital marketing, improving content in line with search engine parameters, and in order to build distinctive website content Large organizations, global brands and specialized websites turn to people with a passion for creativity and knowledge" => 'Building website content means having a professional strategy to create the content on your website pages that is compatible with your goals and the aspirations of your customers, providing information that benefits visitors and followers, using content marketing as an effective means for digital marketing, improving content in line with search engine parameters, and in order to build distinctive website content Large organizations, global brands and specialized websites turn to people with a passion for creativity and knowledge' ,

            "Website content management" => 'Website content management' ,

            "CMS content management is the system that enables you to create content, modify it, and simply control the materials and media provided through various websites, so that it gives the opportunity to create websites and deal with different forms of content directly without the need to write code or study different programming languages, because it contains It contains pre-made instructions, and allows building web pages, publishing content, and saving." => 'CMS content management is the system that enables you to create content, modify it, and simply control the materials and media provided through various websites, so that it gives the opportunity to create websites and deal with different forms of content directly without the need to write code or study different programming languages, because it contains It contains pre-made instructions, and allows building web pages, publishing content, and saving.' ,
            "Commercial website design" => 'Commercial website design' ,
            "Web hosting services" => 'Web hosting services' ,
            "Writing promotional content" => 'Writing promotional content' ,
            "Android application development" => 'Android application development' ,
            "Best website design company" => 'Best website design company' ,
            "The most powerful software company in America and the Arab world" => 'The most powerful software company in America and the Arab world' ,
            "Create a professional online store" => 'Create a professional online store' ,
            "Business identity design" => 'Business identity design' ,
            "What is the best SEO company in the world and the Arab world?" => 'What is the best SEO company in the world and the Arab world?' ,
            "Social media management" => 'Social media management' ,
            "Designing a commercial website is one of the most important tools for online profit, and one of the best and most effective e-marketing tools. Because it has many advantages that are not found in traditional marketing tools, and it is noted that all segments of society have begun to request the services and products they need via the Internet, and in the Arab world the number of individuals who have purchased products and services through the network." => 'Designing a commercial website is one of the most important tools for online profit, and one of the best and most effective e-marketing tools. Because it has many advantages that are not found in traditional marketing tools, and it is noted that all segments of society have begun to request the services and products they need via the Internet, and in the Arab world the number of individuals who have purchased products and services through the network.' ,
            "Web hosting services help websites to exist online; It is like buying a dedicated or shared space on the Internet in order to launch various websites, create e-mail, save files and all forms of electronic content for large institutions, brands, online stores and people as well. Website hosting services vary according to the type and duration of hosting, the size of the site, and the quality of servers and servers; And of course, affect the speed." => 'Web hosting services help websites to exist online; It is like buying a dedicated or shared space on the Internet in order to launch various websites, create e-mail, save files and all forms of electronic content for large institutions, brands, online stores and people as well. Website hosting services vary according to the type and duration of hosting, the size of the site, and the quality of servers and servers; And of course, affect the speed.' ,
            "Writing promotional and marketing content is one of the most important elements of e-marketing. Out of every 5 potential customers, 3 read the marketing content on the internet pages before making a purchase decision. It is not limited to small and emerging companies and institutions, but famous brands are subject to scrutiny through the content they have. Accordingly, the degree of trust that can be obtained, and writing the appropriate promotional content." => 'Writing promotional and marketing content is one of the most important elements of e-marketing. Out of every 5 potential customers, 3 read the marketing content on the internet pages before making a purchase decision. It is not limited to small and emerging companies and institutions, but famous brands are subject to scrutiny through the content they have. Accordingly, the degree of trust that can be obtained, and writing the appropriate promotional content.' ,
            "Developing Android applications means creating applications for smart phones and devices that run on the Android system, and it is noted that these devices are constantly increasing and developing; Google was not satisfied with what it provided of software and technical tools related to the Internet and computers only, but rather its keenness to issue the Android operating program for tablets, phones, watches and smart TVs was one of the most important technologies it provided in the years… " => 'Developing Android applications means creating applications for smart phones and devices that run on the Android system, and it is noted that these devices are constantly increasing and developing; Google was not satisfied with what it provided of software and technical tools related to the Internet and computers only, but rather its keenness to issue the Android operating program for tablets, phones, watches and smart TVs was one of the most important technologies it provided in the years… ' ,
            "Promotion now depends on the existence of websites for all existing goods. Anyone who is keen to create a new brand first resorts to how to market this brand. until it sweeps the market, and through it can reach customers; So, they are interested in looking for a web design company; In order to ensure the spread, and reach the customer in a short period. Designing websites to display trademarks Displaying the trademark So, Tarmeez Tech gives you the solution in the simplest way by creating an attractive and smooth website with an easy-to-use control panel." => 'Promotion now depends on the existence of websites for all existing goods. Anyone who is keen to create a new brand first resorts to how to market this brand. until it sweeps the market, and through it can reach customers; So, they are interested in looking for a web design company; In order to ensure the spread, and reach the customer in a short period. Designing websites to display trademarks Displaying the trademark So, Tarmeez Tech gives you the solution in the simplest way by creating an attractive and smooth website with an easy-to-use control panel.' ,
            "In light of the current technological development, many software companies must emerge, which have an indispensable role in designing and developing many websites and programs, as they have a role in organizing instructions for running programs, as well as updating the version of programs, and following up on how they work from Through an integrated team of programmers, who have sufficient training and skills that enable them to test the best and latest tools and programming languages, we at Tarmeez Tech always strive to be the best among the many companies in the arena." => 'In light of the current technological development, many software companies must emerge, which have an indispensable role in designing and developing many websites and programs, as they have a role in organizing instructions for running programs, as well as updating the version of programs, and following up on how they work from Through an integrated team of programmers, who have sufficient training and skills that enable them to test the best and latest tools and programming languages, we at Tarmeez Tech always strive to be the best among the many companies in the arena.' ,
            "Do you dream of creating your own online store to expand your business? Especially after the increase in the percentage of sales that take place electronically, which is expected to accelerate in the coming years, we are well aware that the idea of ​​creating a professional online store is somewhat terrifying, especially if you do not have sufficient background in the technical field, but do not worry, as we will present a guide today Comprehensive on how to create through the free consultation that was prepared for you, do not hesitate to contact us in order to answer all your inquiries on this subject." => 'Do you dream of creating your own online store to expand your business? Especially after the increase in the percentage of sales that take place electronically, which is expected to accelerate in the coming years, we are well aware that the idea of ​​creating a professional online store is somewhat terrifying, especially if you do not have sufficient background in the technical field, but do not worry, as we will present a guide today Comprehensive on how to create through the free consultation that was prepared for you, do not hesitate to contact us in order to answer all your inquiries on this subject.' ,
            "A simple brand identification is the name, design, symbol or any feature that identifies your products or services in a way that makes you stand out and unique.
            Think of it as the idea or image that comes to people's minds when they think of a product or service. A brand is not only about the attributes of a product or service but also about the feelings and emotions it brings to the user. Where people tend to build emotional bonds towards products and brands. It is their affections for the company or its products that build their loyalty. Once they see a name, logo, message, or visual identity, their feelings will be affected." => 'A simple brand identification is the name, design, symbol or any feature that identifies your products or services in a way that makes you stand out and unique.
            Think of it as the idea or image that comes to people minds when they think of a product or service. A brand is not only about the attributes of a product or service but also about the feelings and emotions it brings to the user. Where people tend to build emotional bonds towards products and brands. It is their affections for the company or its products that build their loyalty. Once they see a name, logo, message, or visual identity, their feelings will be affected.' ,
            "Promotion is the basis of any process now, and through it the economy of many is built; Therefore, interest in the best SEO companies in the Arab world is a means to reach the goal of global marketing, and the Tarmeez Tech company is a leader in the world of SEO, which gives you results through unique SEO services that are compatible with all the standards that have been set, as the company guarantees you the lead in search results in record time Your site will appear in the results." => 'Promotion is the basis of any process now, and through it the economy of many is built; Therefore, interest in the best SEO companies in the Arab world is a means to reach the goal of global marketing, and the Tarmeez Tech company is a leader in the world of SEO, which gives you results through unique SEO services that are compatible with all the standards that have been set, as the company guarantees you the lead in search results in record time Your site will appear in the results.' ,
            "Home" => 'الرئيسية'
    ];
