<?php

    return [

            "Blog" => 'المدونة' ,
            "Building content for the site" => 'بناء محتوى للموقع ' ,
            "Building website content means having a professional strategy to create the content on your website pages that is compatible with your goals and the aspirations of your customers, providing information that benefits visitors and followers, using content marketing as an effective means for digital marketing, improving content in line with search engine parameters, and in order to build distinctive website content Large organizations, global brands and specialized websites turn to people with a passion for creativity and knowledge" => 'بناء محتوى المواقع يعني وجود استراتيجية احترافية لإنشاء المحتوى الموجود على صفحات موقعك الإلكتروني تتوافق مع أهدافك وتطلعات عملائك، وتقديم المعلومات التي تفيد الزوار والمتابعين، واستخدام التسويق بالمحتوى كوسيلة فعالة للتسويق الرقمي، وتحسين المحتوى بما يتوافق مع محددات محركات البحث، ومن أجل بناء محتوى المواقع المميز تلجأ المؤسسات الكبيرة والعلامات التجارية العالمية ومواقع الويب المتخصصة إلى الأشخاص الشغوفين بالإبداع ومعرفة .' ,
            "Website content management" => 'ادارة محتوى الموقع ' ,
            "CMS content management is the system that enables you to create content, modify it, and simply control the materials and media provided through various websites, so that it gives the opportunity to create websites and deal with different forms of content directly without the need to write code or study different programming languages, because it contains It contains pre-made instructions, and allows building web pages, publishing content, and saving." => 'إدارة محتوى المواقع CMS هو النظام الذي يُمكنك من إنشاء المحتوى وتعديله والتحكم في المواد والوسائط المقدمة عبر المواقع الإلكترونية المختلفة ببساطة، بحيث يعطي فرصة إنشاء مواقع الويب والتعامل مع أشكال المحتوى المختلفة بصورة مباشرة بدون الحاجة إلى كتابة التعليمات البرمجية أو دراسة لغات البرمجة المختلفة، لأنه يحتوي على تعليمات معدة بشكل مسبق، ويسمح ببناء صفحات الإنترنت، ونشر المحتوى، وحفظه' ,
            "Commercial website design" => 'تصميم موقع الكتروني تجاري ' ,
            "Web hosting services" => 'خدمات استضافة المواقع ' ,
            "Writing promotional content" => 'كتابة المحتوى الدعائي ' ,
            "Android application development" => 'تطوير تطبيقات الاندرويد ' ,
            "Best website design company" => 'افضل شركة تصميم موقع الكتروني ' ,
            "The most powerful software company in America and the Arab world" => 'اقوى شركة برمجيات في امريكا والوطن العربي ' ,
            "Create a professional online store" => 'انشاء متجر الكتروني احترافي ' ,
            "Business identity design" => 'تصميم الهوية التجارية ' ,
            "What is the best SEO company in the world and the Arab world?" => 'ماهي افضل شركة سيو في العالم والوطن العربي ؟' ,
            "Social media management" => 'ادارة السوشل ميديا ' ,
            "Designing a commercial website is one of the most important tools for online profit, and one of the best and most effective e-marketing tools. Because it has many advantages that are not found in traditional marketing tools, and it is noted that all segments of society have begun to request the services and products they need via the Internet, and in the Arab world the number of individuals who have purchased products and services through the network." => 'تصميم موقع إلكتروني تجاري أحد أهم أدوات الربح عن طريق الإنترنت، ومن أفضل أدوات التسويق الإلكتروني وأكثرها فاعلية؛ لأنه يمتلك العديد من الميزات التي لا تتواجد في أدوات التسويق التقليدية، ومن الملاحظ أن جميع فئات المجتمع قد بدأت في طلب ما تحتاجه من خدمات ومنتجات عبر الانترنت، وفي الوطن العربي بلغ عدد الأفراد الذين قاموا بشراء منتجات وخدمات عبر شبكة .' ,
            "Web hosting services help websites to exist online; It is like buying a dedicated or shared space on the Internet in order to launch various websites, create e-mail, save files and all forms of electronic content for large institutions, brands, online stores and people as well. Website hosting services vary according to the type and duration of hosting, the size of the site, and the quality of servers and servers; And of course, affect the speed." => 'خدمات استضافة المواقع تساعد مواقع الويب على التواجد عبر الإنترنت؛ فهي بمثابة شراء مساحة مخصصة أو مشتركة على الإنترنت من أجل إطلاق مواقع الويب المختلفة وإنشاء البريد الإلكتروني، وحفظ الملفات وكل أشكال المحتوى الإلكتروني للمؤسسات الكبيرة والعلامات التجارية والمتاجر الإلكترونية والأشخاص أيضًا، وتتنوع خدمات استضافة المواقع الإلكترونية حسب نوعية الاستضافة ومدتها وحجم الموقع وجودة السيرفرات والخوادم؛ وتؤثر بالطبع على سرعة .' ,
            "Writing promotional and marketing content is one of the most important elements of e-marketing. Out of every 5 potential customers, 3 read the marketing content on the internet pages before making a purchase decision. It is not limited to small and emerging companies and institutions, but famous brands are subject to scrutiny through the content they have. Accordingly, the degree of trust that can be obtained, and writing the appropriate promotional content." => 'كتابة المحتوى الدعائي والتسويقي من أهم عناصر التسويق الإلكتروني، فمن بين كل 5 عملاء محتملين يقوم 3 بقراءة المحتوى التسويقي الموجود على صفحات الإنترنت قبل اتخاذ قرار الشراء، ولا يختص الأمر بالشركات والمؤسسات الصغيرة والناشئة بل تعتبر العلامات التجارية المشهورة محل تدقيق عن طريق المحتوى الموجود لديها، وبناء عليه تكون درجة الثقة التي يمكن الحصول عليها، وكتابة المحتوى الدعائي المناسب .' ,
            "Developing Android applications means creating applications for smart phones and devices that run on the Android system, and it is noted that these devices are constantly increasing and developing; Google was not satisfied with what it provided of software and technical tools related to the Internet and computers only, but rather its keenness to issue the Android operating program for tablets, phones, watches and smart TVs was one of the most important technologies it provided in the years… " => 'تطوير تطبيقات الاندرويد يعني إنشاء التطبيقات الخاصة بالهواتف والأجهزة الذكية التي تعمل بنظام أندرويد، ومن الملاحظ أن هذه الأجهزة في زيادة وتطور مستمرين؛ فلم تكتف شركة  Google  بما قدمته من برمجيات وأدوات تقنية متعلقة بالإنترنت وأجهزة الكمبيوتر فقط، بل كان حرصها على إصدار برنامج التشغيل  Android الخاص بالأجهزة اللوحية والهواتف والساعات والتلفزيونات الذكية من أهم التقنيات التي قدمتها في السنوات ...' ,
            "Promotion now depends on the existence of websites for all existing goods. Anyone who is keen to create a new brand first resorts to how to market this brand. until it sweeps the market, and through it can reach customers; So, they are interested in looking for a web design company; In order to ensure the spread, and reach the customer in a short period. Designing websites to display trademarks Displaying the trademark So, Tarmeez Tech gives you the solution in the simplest way by creating an attractive and smooth website with an easy-to-use control panel." => 'يعتمد الترويج الآن على وجود مواقع إلكترونية لكل السلع الموجودة حاليًا، فأي شخص حريص على تكوين براند جديد أول ما يلجأ إليه كيفية تسويق هذا البراند؛ حتى يجتاح السوق، ويستطيع من خلاله الوصول للعملاء؛ لذلك يهتمون بالبحث عن شركة تصميم مواقع إلكترونية ؛ حتى يضمنوا الانتشار، والوصول للعميل في فترة قصيرة. تصميم مواقع الكترونية لعرض العلامات التجارية  عرض العلامة التجارية لذا فشركة ترميز تك تعطيك الحل بابسط الطرق من خلال انشاء موقع الكتروني جذاب وسلس مع لوحة تحكم سهلة الاستخدام .' ,
            "In light of the current technological development, many software companies must emerge, which have an indispensable role in designing and developing many websites and programs, as they have a role in organizing instructions for running programs, as well as updating the version of programs, and following up on how they work from Through an integrated team of programmers, who have sufficient training and skills that enable them to test the best and latest tools and programming languages, we at Tarmeez Tech always strive to be the best among the many companies in the arena." => 'فى ظل التطور التكنولوجى الحالي، لا بد من ظهور العديد من شركات البرمجيات، والتي لها دور لا نغض الطرف عنه فى تصميم، وتطوير الكثير من  المواقع والبرامج، حيث لها دور فى تنظيم تعليمات  لتشغيل البرامج، كما تقوم بتحديث إصدار البرامج، ومتابعة طريقة عملها من خلال فريق متكامل من المبرمجين، وهم على قدر كافٍ من التدريب والمهارات التي تمكنهم من اختبار افضل واحدث الادوات والغات البرمجية نحن في شركة ترميز تك نسعى دائماً لنكون الافضل من بين العديد من الشركات الموجودة في الساحة .' ,
            "Do you dream of creating your own online store to expand your business? Especially after the increase in the percentage of sales that take place electronically, which is expected to accelerate in the coming years, we are well aware that the idea of ​​creating a professional online store is somewhat terrifying, especially if you do not have sufficient background in the technical field, but do not worry, as we will present a guide today Comprehensive on how to create through the free consultation that was prepared for you, do not hesitate to contact us in order to answer all your inquiries on this subject." => 'هل تحلم بإنشاء متجرك الإلكتروني الخاص بك لتوسيع أعمالك التجارية؟ وخصوصًا بعدما ازدادت نسبة المبيعات التي تتم إلكترونيًا، والتي من المتوقع أن تتسارع في السنوات القادمة، نعي جيدًا أن فكرة إنشاء متجر إلكتروني احترافي مرعبة إلى حد ما، وخاصةً إذا لم يكن لديك خلفية كافية في المجال التقني، لكن لا داعي للقلق فنحن سنقدم اليوم دليلًا شاملًا بشأن كيفية إنشاء من خلال الاستشارة المجانية التي تم تجهيزها من اجلك لا تتردد في التواصل معنا لكي نجيب عن جميع استفساراتك في هذا الموضوع .' ,
            "A simple brand identification is the name, design, symbol or any feature that identifies your products or services in a way that makes you stand out and unique.
            Think of it as the idea or image that comes to people's minds when they think of a product or service. A brand is not only about the attributes of a product or service but also about the feelings and emotions it brings to the user. Where people tend to build emotional bonds towards products and brands. It is their affections for the company or its products that build their loyalty. Once they see a name, logo, message, or visual identity, their feelings will be affected." => ' التعريف البسيط للعلامة التجارية هو الاسم أو التصميم أو الرمز أو أي ميزة تحدد منتجاتك أو خدماتك بطريقة تجعلك مميزًا وفريدًا.
            فكر في الأمر على أنه الفكرة أو الصورة التي تتبادر إلى أذهان الناس عندما يفكرون في منتج أو خدمة. لا تتعلق العلامة التجارية بسمات المنتج او الخدمة فحسب ، بل تتعلق أيضًا بالمشاعر والعواطف التي تجلبها للمستخدم. حيث يميل الناس إلى بناء روابط عاطفية تجاه المنتجات والبراند. إن عواطفهم تجاه الشركة أو منتجاتها هي التي تبني ولائهم. بمجرد أن يروا الاسم أو الشعار أو الرسالة أو الهوية المرئية ، ستتأثر مشاعرهم.' ,
            "Promotion is the basis of any process now, and through it the economy of many is built; Therefore, interest in the best SEO companies in the Arab world is a means to reach the goal of global marketing, and the Tarmeez Tech company is a leader in the world of SEO, which gives you results through unique SEO services that are compatible with all the standards that have been set, as the company guarantees you the lead in search results in record time Your site will appear in the results." => 'أصبحت مهمة إدارة مواقع التواصل الاجتماعي  ( السوشل ميديا ) من المهام الرئيسية التي لا يمكن الاستغناء عنها داخل أي نشاط تجاري مهما كان حجمه. إذ يوجد اليوم حوالي 3.78 مليار مستخدم لوسائل التواصل الاجتماعي حول العالم ويرتفع هذا الرقم سنويًا بشكل منتظم. وبالتالي يتحتم عليك معرفة ماهي الشركة المناسبة لادارة نشاطك التجاري  على شبكات التواصل الاجتماعي بطريقة فعّالة للوصول لأكبر عدد من شريحة عملائك المحتملين.' ,
            "Home" => 'الرئيسية'
    ];
